version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
      LANG: ja_JP.utf8
      LC_ALL: ja_JP.utf8
    ports:
      - "5432:5432"
    user: "${UID_GID}"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql